{
  "message": "TypeError: 'float' object cannot be interpreted as an integer\n\u001b[90mRun \u001b]8;;rstudio:run:reticulate::py_last_error()\u0007`reticulate::py_last_error()`\u001b]8;;\u0007 for details.\u001b[39m",
  "traceback": ["py_call_impl(callable, call_args$unnamed, call_args$named)", "model$fit(x = x_train, y = y_train, epochs = 100, batch_size = FLAGS$batch_size, \n    validation_split = 0.2, callbacks = list(callback_early_stopping(patience = 10, \n        restore_best_weights = TRUE)), verbose = 0)", "eval(ei, envir)", "eval(ei, envir)", "withVisible(eval(ei, envir))", "tuning_run(\"train_model.R\", flags = list(units1 = c(32, 64, 128), \n    units2 = c(16, 32, 64), dropout1 = c(0.2, 0.3, 0.4), lr = c(0.001, \n        5e-04), batch_size = c(128, 256)))"]
}
